name: Express Testing
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"

      # Check out a copy of the repo's code so we can use it in this automation workflow
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          node-version: 'latest'

      # Install NPM packages such as Express
      - name: Install dependencies for our project
        run: npm install

      # Run our project's `test` command to actually run the test
      - name: Actually run the tests, finally!
        run: npm run test
